M48
; DRILL file {KiCad (6.0.2-0)} date 2022 August 15, Monday 15:04:23
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-15T15:04:23+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X68.0Y-45.0
X68.0Y-99.0
X117.348Y-115.634
X132.0Y-45.0
X132.0Y-99.0
T0
M30
